language: php

php:
  - 5.6
  - 7

cache:
  directories:
    - ~/.composer

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - ant
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master